name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure temporary deploy directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || '22' }}
          script: |
            mkdir -p ${{ secrets.EC2_DEPLOY_PATH }}/tmp-deploy

      - name: Upload deploy script
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || '22' }}
          source: deploy/ec2-deploy.sh
          target: ${{ secrets.EC2_DEPLOY_PATH }}/tmp-deploy/

      - name: Run remote deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || '22' }}
          script: |
            chmod +x ${{ secrets.EC2_DEPLOY_PATH }}/tmp-deploy/ec2-deploy.sh
            ${{ secrets.EC2_DEPLOY_PATH }}/tmp-deploy/ec2-deploy.sh ${{ secrets.EC2_DEPLOY_PATH }} ${{ secrets.EC2_COMPOSE_FILE || 'docker-compose.yml' }}
            rm -rf ${{ secrets.EC2_DEPLOY_PATH }}/tmp-deploy
